"""adding_geom_table_to_markers_and_discussions

Revision ID: 42a9d996397a
Revises: 41aa96fd6464
Create Date: 2018-07-14 00:14:00.648053

"""

# revision identifiers, used by Alembic.
revision = '42a9d996397a'
down_revision = '41aa96fd6464'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('geom', ga.Geometry('POINT', srid=4326)))
    #op.update_column('markers', ga.functions.ST_Transform( 'geom', 4326))
    conn = op.get_bind()
    conn.execution_options(isolation_level="AUTOCOMMIT")
    conn.execute('UPDATE markers SET geom = ST_SetSRID(ST_MakePoint(longitude,latitude),4326);')
    conn.execute('CREATE INDEX idx_markers_geom ON markers USING GIST(geom);')
    conn.execute("SELECT AddGeometryColumn('public','discussions','geom',4326,'POINT',2);")
    conn.execute('UPDATE discussions SET geom = ST_SetSRID(ST_MakePoint(longitude,latitude),4326);')
    conn.execute('CREATE INDEX idx_discussions_geom ON discussions USING GIST(geom);')
    conn.execute('VACUUM ANALYZE;')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execution_options(isolation_level="AUTOCOMMIT")
    conn.execute('DROP INDEX idx_markers_geom;')
    op.drop_column('markers', 'geom')
    conn.execute('DROP INDEX idx_discussions_geom;')
    op.drop_column('discussions', 'geom')
    ### end Alembic commands ###
