"""create_postgis_extensions

Revision ID: v123456
Revises: 3c0d35fdbe2e
Create Date: 2018-03-07 13:49:06.780319

"""

# revision identifiers, used by Alembic.
revision = 'v123456'
down_revision = '3c0d35fdbe2e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('test_column', sa.Float(), nullable=True))
    conn = op.get_bind()
    conn.execution_options(isolation_level="AUTOCOMMIT")
    conn.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    conn.execute('CREATE EXTENSION IF NOT EXISTS postgis_topology;')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execution_options(isolation_level="AUTOCOMMIT")
    conn.execute('DROP EXTENSION postgis_topology;')
    conn.execute('DROP EXTENSION postgis;')
    conn.execute('DROP SCHEMA IF EXISTS topology CASCADE;')
    conn.execute('VACUUM ANALYZE;')
    ### end Alembic commands ###
